name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd backend && docker build -t ${{ secrets.ECR_REPO_URL }}:backend-${{ github.sha }} .
      - run: aws eks update-kubeconfig --region us-east-1 --name your-cluster-name
      - run: cd backend/k8s && kustomize edit set image backend=${{ secrets.ECR_REPO_URL }}:backend-${{ github.sha }}
      - run: cd backend/k8s && kustomize build | kubectl apply -f -