name: Backend CI

on:
  pull_request:
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd starter/backend && pipenv install --dev
      - run: cd starter/backend && pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd starter/backend && pipenv install --dev
      - run: cd starter/backend && pipenv run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd starter/backend && pipenv install --dev
      - run: cd starter/backend && docker build -t mp-backend:latest .
